on:
  push:
    branches:
      - main
      - master

name: deployconnect

jobs:
  deployconnect:
    runs-on: macOS-latest
    env:
      APP_NAME: "GHA_SHINYTEST_RSC"
      APP_DIR: "app"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_URL: ${{ secrets.RSCONNECT_URL }}
      RSCONNECT_USERNAME: ${{ secrets.RSCONNECT_USERNAME }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}

      - name: Restore Environment
        run: |
          renv::restore()
        shell: Rscript {0}

      - name: Install shinytest dependencies
        run: |
          shinytest::install_dependencies()
        shell: Rscript {0}

      - name: Run Shinytests
        run: |
          shinytest::testApp("${{ env.APP_DIR }}")
        shell: Rscript {0}

      - name: Authenticate with RStudio Connect
        run: |
          rsconnect::addConnectServer(url = "${{ env.RSCONNECT_URL}}",
                            name = "rsc_server")
          rsconnect::connectApiUser(account = "${{ env.RSCONNECT_USERNAME }}",
                          server = "rsc_server",
                          apiKey = "${{ env.RSCONNECT_APIKEY }}",
                          quiet = FALSE)
        shell: Rscript {0}

      - name: Deploy App
        run: |
          rsconnect::deployApp(appDir = "${{ env.APP_DIR }}",
                     appName = "${{ env.APP_NAME }}",
                     account = "${{ env.RSCONNECT_USERNAME }}",
                     server = "rsc_server")
        shell: Rscript {0}
